# Generated by Django 5.2.1 on 2026-03-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_number_of_rooms_property_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('market_adr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_occupancy', models.FloatField()),
                ('paf', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('pace_threshold', models.DecimalField(decimal_places=2, default=0.95, max_digits=5)),
                ('nights_low_threshold', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('nights_high_threshold', models.DecimalField(decimal_places=2, default=1.05, max_digits=5)),
                ('adr_low_threshold', models.DecimalField(decimal_places=2, default=0.9, max_digits=5)),
                ('adr_high_threshold', models.DecimalField(decimal_places=2, default=1.15, max_digits=5)),
                ('early_month_guard_days', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'month')},
            },
        ),
    ]
