# Generated by Django 5.2.1 on 2026-03-27 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_number_of_rooms_property_room_type_and_more'),
        ('property_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='adr_high_threshold',
            field=models.DecimalField(decimal_places=2, default=1.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='adr_low_threshold',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='market_occupancy',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='month',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'Format must be YYYY-MM')]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='nights_high_threshold',
            field=models.DecimalField(decimal_places=2, default=1.05, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='nights_low_threshold',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='propertyconfig',
            name='pace_threshold',
            field=models.DecimalField(decimal_places=2, default=0.95, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddIndex(
            model_name='propertyconfig',
            index=models.Index(fields=['property', 'month'], name='property_co_propert_ec64c7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyconfig',
            index=models.Index(fields=['month'], name='property_co_month_2121a1_idx'),
        ),
    ]
