# Generated by Django 5.2.12 on 2026-03-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0002_property_number_of_rooms_property_room_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPropertyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_type', models.CharField(choices=[('actual', 'Actual'), ('otb', 'On The Books')], default='actual', max_length=10)),
                ('rooms', models.IntegerField(default=0)),
                ('arrivals', models.IntegerField(default=0)),
                ('departures', models.IntegerField(default=0)),
                ('stay_over', models.IntegerField(default=0)),
                ('bed_nights', models.IntegerField(default=0)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_room_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_guest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('occupancy_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('guest_per_room', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='properties.property')),
            ],
            options={
                'ordering': ['-date', 'property', 'data_type'],
                'indexes': [models.Index(fields=['date', 'data_type'], name='daily_metri_date_a32df5_idx'), models.Index(fields=['property', 'date'], name='daily_metri_propert_485c97_idx')],
                'unique_together': {('property', 'date', 'data_type')},
            },
        ),
    ]
