# Generated by Django 6.0.3 on 2026-03-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occupancy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bookings', models.PositiveIntegerField(default=0)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='properties.property')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('property', 'month')},
            },
        ),
    ]
