# Generated by Django 5.2.12 on 2026-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='room_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1B', '1 Bedroom'), ('2B', '2 Bedroom'), ('3B', '3 Bedroom'), ('4B', '4 Bedroom'), ('5B', '5 Bedroom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
